select assure.num_ref, assure.id_assure, assure.id_bci, 
Ks.Id_event, Ks.Date_Mammo, 
If(Ks.Comp_Re_1D="S","anomalie SD plus suspecte",
If(Ks.Comp_Re_1D="S","anomalie SD apparue"," ")) as comparaison_SD,
If(Ks.Comp_Re_1G="S","anomalie SG plus suspecte",
If(Ks.Comp_Re_1G="S","anomalie SG apparue"," ")) as comparaison_SG,
if(Ks.Exam_Clini="A","Anormal",if(Ks.Exam_Clini="N","Normal",if(Ks.Exam_Clini="R","Refusé"," "))) as ECS, 
Ks.Acr_SD11 as L1_ACR_SD,
Ks.ACR_SG11 as L1_ACR_SG,
if(Ks.Suspec11_D="A","Opacité à contour spiculé", 
if(Ks.Suspec11_D="B","Opacité à contour non spiculé", 
if(Ks.Suspec11_D="C","Microcalcifications", 
if(Ks.Suspec11_D="D","Opacité avec Microcalcifications", 
if(Ks.Suspec11_D="E","Anomalie Architecturale", 
if(Ks.Suspec11_D="F","Densité focale Asymétrique", 
if(Ks.Suspec11_D="G","Autres anomalie"," "))))))) as L1_Type_Image_SD,
if(Ks.Suspec11_G="A","Opacité à contour spiculé", 
if(Ks.Suspec11_G="B","Opacité à contour non spiculé", 
if(Ks.Suspec11_G="C","Microcalcifications", 
if(Ks.Suspec11_G="D","Opacité avec Microcalcifications", 
if(Ks.Suspec11_G="E","Anomalie Architecturale", 
if(Ks.Suspec11_G="F","Densité focale Asymétrique", 
if(Ks.Suspec11_G="G","Autres anomalie"," "))))))) as L1_Type_Image_SG,
if(Ks.Echo_l1="O","Echo réalisé sur mammo négative","Non") as Echo_L1,
if(Ks.Echo_L1_Suspecte="O","Echo_L1_Suspecte","Non") as Echo_ECS_L1_Suspecte,
if(Ks.Bilan_L1="O","Bilan immédiat nécessaire","Pas de BDI") as BDI,
if(Ks.Bi_Agrand="O","BDI_Agrandissement","Non") as BDI_Agrandissement,
if(Ks.Bi_Cyto="O","BDI_Cytoponction","Non") as BDI_Cytoponction,
if(Ks.Bi_Echo="O","BDI_Echographie","Non") as BDI_Echographie,
Ks.Acr_Sd1 as BDI_ACR_SD,
Ks.Acr_Sg1 as BDI_ACR_SG,
if(Ks.Suspec1_Sd="A","Opacité à contour spiculé", 
if(Ks.Suspec1_Sd="B","Opacité à contour non spiculé", 
if(Ks.Suspec1_Sd="C","Microcalcifications", 
if(Ks.Suspec1_Sd="D","Opacité avec Microcalcifications", 
if(Ks.Suspec1_Sd="E","Anomalie Architecturale", 
if(Ks.Suspec1_Sd="F","Densité focale Asymétrique", 
if(Ks.Suspec1_Sd="G","Autres anomalie"," "))))))) as BDI_Type_Image_SD,
if(Ks.Suspec1_Sg="A","Opacité à contour spiculé", 
if(Ks.Suspec1_Sg="B","Opacité à contour non spiculé", 
if(Ks.Suspec1_Sg="C","Microcalcifications", 
if(Ks.Suspec1_Sg="D","Opacité avec Microcalcifications", 
if(Ks.Suspec1_Sg="E","Anomalie Architecturale", 
if(Ks.Suspec1_Sg="F","Densité focale Asymétrique", 
if(Ks.Suspec1_Sg="G","Autres anomalie"," "))))))) as BDI_Type_Image_SG,
if(Ks.Exam_Cons1 IN ("S03","S04","S05","S06","S09","S12","S18","S24") or Ks.Exam_Cons_Echo_L1 IN ("S03","S04","S05","S06","S09","S12","S18","S24"),"Surveillance","Non") as BDI_CAT_Surveillance,
if(Ks.Exam_Cons1 IN ("PCY") or Ks.Exam_Cons_Echo_L1 IN ("PCY"),"Exam_Cytoponction","Non") as BDI_CAT_Cytoponction,
if(Ks.Exam_Cons1 IN ("PMI") or Ks.Exam_Cons_Echo_L1 IN ("PMI"),"Exam_Microbiopsie","Non") as BDI_CAT_Microbiopsie,
if(Ks.Exam_Cons1 IN ("PMA") or Ks.Exam_Cons_Echo_L1 IN ("PMA"),"Exam_Macrobiopsie","Non") as BDI_CAT_Macrobiopsie,
if(Ks.Exam_Cons1 IN ("AUT","IRM","PCH","PRP") or Ks.Exam_Cons_Echo_L1 IN ("AUT","IRM","PCH","PRP"),"Autre Prise en Charge","Non") as BDI_CAT_AutrePEC,
Ks.Acr_Sd2 as L2_ACR_SD_SD,
Ks.Acr_Sg2 as L2_ACR_SD_SG,
if(Ks.Suspec2_Sd="A","Opacité à contour spiculé", 
if(Ks.Suspec2_Sd="B","Opacité à contour non spiculé", 
if(Ks.Suspec2_Sd="C","Microcalcifications", 
if(Ks.Suspec2_Sd="D","Opacité avec Microcalcifications", 
if(Ks.Suspec2_Sd="E","Anomalie Architecturale", 
if(Ks.Suspec2_Sd="F","Densité focale Asymétrique", 
if(Ks.Suspec2_Sd="G","Autres anomalie"," "))))))) as L2_Type_Image_SD,
if(Ks.Suspec2_Sg="A","Opacité à contour spiculé", 
if(Ks.Suspec2_Sg="B","Opacité à contour non spiculé", 
if(Ks.Suspec2_Sg="C","Microcalcifications", 
if(Ks.Suspec2_Sg="D","Opacité avec Microcalcifications", 
if(Ks.Suspec2_Sg="E","Anomalie Architecturale", 
if(Ks.Suspec2_Sg="F","Densité focale Asymétrique", 
if(Ks.Suspec2_Sg="G","Autres anomalie"," "))))))) as L2_Type_Image_SG,

if(Ks.Exam_Cons2 IN ("S03","S04","S05","S06","S09","S12","S18","S24"),"Surveillance","Non") as L2_CAT_Surveillance,
if(Ks.Exam_Cons2 IN ("PCY"),"Exam_Cytoponction","Non") as L2_CAT_Cytoponction,
if(Ks.Exam_Cons2 IN ("PMI"),"Exam_Microbiopsie","Non") as L2_CAT_Microbiopsie,
if(Ks.Exam_Cons2 IN ("PMA"),"Exam_Macrobiopsie","Non") as L2_CAT_Macrobiopsie,
if(Ks.Exam_Cons2 IN ("AUT","IRM","PCH","PRP"),"Autre Prise en Charge","Non") as L2_CAT_AutrePEC,
ks.resultat as resultat_global_L1L2
from assure join ks using (id_assure)
where ks.date_mammo between "date1" and "date2"