---
- name: input folder exists
  file:
    path: "{{ dp_home }}/data/{{ item }}"
    state: directory
    mode: u=rwx,g=,o=,g+s
  become_user: "{{ ssh_user }}"
  with_items:
  - input
  - input/crcdc
  - input/epiconcept
  - input/esis
  - input/hdh
  - input/neo
  - output
  - output/cnam
  - output/hdh
- name: getting input data from sftp
  shell: |
          echo get input_data/{{ item }} {{ dp_home }}/data/{{ item }}  | sftp -o StrictHostKeyChecking=no -b - {{ sftp_user }}@{{ sftp_server }}  
  become_user: "{{ ssh_user }}"
  tags: [sftp]
  with_items:
  - input/crcdc/refusing-list.csv
  - input/epiconcept/mapping-table.csv
  - input/esis/esis_dicom_guid.parquet
  - input/hdh/p11_encryption_public.rsa
  - input/neo/extraction_neoscope.zip
  - input/mammogram_words
  - output/cnam/duplicates_to_keep.csv
  - output/cnam/safe.zip
  - output/hdh/p11_transfer_private_key.rsa
  - output/hdh/p11_transfer_public_key.rsa
