name: Deep.piste Continuous Integration

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["feature/dcm-deid-png"]

jobs:
  codebase-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Ensure Default Package Manager is up to date
        run: python3 -m pip install --upgrade pip setuptools wheel
      -
        name: Install Deep.piste Package
        run: pip install -e .[quality-tools]
      -
        name: Test with Pytest
        run: pytest